# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.1.4
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.610-1
    hooks:
    -   id: mypy
-   repo: https://github.com/miki725/importanize/
    rev: 'master'
    hooks:
    -   id: importanize
        args: [--verbose]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
